{"name": "test_no_auth", "status": "failed", "statusDetails": {"message": "AssertionError: Unexpected code: 500", "trace": "def test_no_auth():\n>       GetAvailableSimulatorModels().request().verify_response(error_code=400)\n\ntests/enduser/test_get_available_simulator_models.py:35: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <qa.api.enduser.calls.GetAvailableSimulatorModels object at 0x10424d400>, error_code = 400, resp_body = None\nignore_order = False, exclude_paths = None, normalize = False\n\n    def verify_response(self, error_code=None, resp_body=None,\n                        ignore_order=False, exclude_paths=None,\n                        normalize=False):\n        if error_code:\n>           assert self.response.status_code == error_code, (\n                f'Unexpected code: {self.response.status_code}'\n            )\nE           AssertionError: Unexpected code: 500\n\nqa/tools/caller.py:83: AssertionError"}, "start": 1648640658463, "stop": 1648640658839, "uuid": "49b35a2a-a5ae-44a0-94e7-35a8840b3d63", "historyId": "f219f537afa42d7c57da611f8d4684ec", "testCaseId": "c3137efe3caa38b10f7511fe33de9543", "fullName": "tests.enduser.test_get_available_simulator_models#test_no_auth", "labels": [{"name": "parentSuite", "value": "tests.enduser"}, {"name": "suite", "value": "test_get_available_simulator_models"}, {"name": "host", "value": "Elenas-MacBook-Pro.local"}, {"name": "thread", "value": "59719-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.enduser.test_get_available_simulator_models"}]}