{"name": "test_no_auth", "status": "failed", "statusDetails": {"message": "AssertionError: Unexpected code: 500", "trace": "def test_no_auth():\n>       PredictTicketText().request().verify_response(error_code=400)\n\ntests/enduser/test_predict_ticket_text.py:38: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <qa.api.enduser.calls.PredictTicketText object at 0x1042a36a0>, error_code = 400, resp_body = None\nignore_order = False, exclude_paths = None, normalize = False\n\n    def verify_response(self, error_code=None, resp_body=None,\n                        ignore_order=False, exclude_paths=None,\n                        normalize=False):\n        if error_code:\n>           assert self.response.status_code == error_code, (\n                f'Unexpected code: {self.response.status_code}'\n            )\nE           AssertionError: Unexpected code: 500\n\nqa/tools/caller.py:83: AssertionError"}, "start": 1648640666381, "stop": 1648640666755, "uuid": "6a8d6069-94cc-4b3c-8cc9-cb7e5879b7f8", "historyId": "516894f2ce9549d0329c6e79c96ff941", "testCaseId": "1d811d226b6a80b5e44cad6ecf9d6163", "fullName": "tests.enduser.test_predict_ticket_text#test_no_auth", "labels": [{"name": "parentSuite", "value": "tests.enduser"}, {"name": "suite", "value": "test_predict_ticket_text"}, {"name": "host", "value": "Elenas-MacBook-Pro.local"}, {"name": "thread", "value": "59719-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.enduser.test_predict_ticket_text"}]}